version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - .env
    ports:
      - "8571:80"
      - "3071:80"
    volumes:
      - .:/app

